version: "3.6"
services:
  app:
    image: dostorlinux/simple-slep
    container_name: simple2_web
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env
    working_dir: /var/www/simple
    volumes:
      - ./:/var/www/simple
    networks:
      - esnet
    depends_on:
      - db
      - redis
      - elasticsearch
  redis:
    image: "redis"
    container_name: simple2_redis
    networks:
      - esnet
    ports:
      - "${REDIS_PORT}:6379"
    depends_on:
      - db
  elasticsearch:
    image: "elasticsearch:5.6"
    container_name: simple2_elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - esnet
    depends_on:
      - db
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: simple2_rabbit
    hostname: "simple_rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      DOWNLOADS_MAX_JOBS_PER_USER: ${DOWNLOADS_MAX_JOBS_PER_USER}
    ports:
      - "${RABBITMQ_PORT_MANAGER}:15672"
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - esnet

#Docker Volumes

#Docker Networks
networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
